CREATE TABLE PARTY (
    PARTY_ID UUID NOT NULL DEFAULT gen_random_uuid(),
    CODE VARCHAR(6) NOT NULL,
    HOST_ACCESS_TOKEN VARCHAR(256) NOT NULL,
    HOST_REFRESH_TOKEN VARCHAR(256) NOT NULL,
    PRIMARY KEY (PARTY_ID)
)
